version: '3'
services:
    myfluentd:
        build: .
        network_mode: "host"
        container_name: "fluentd"
#        logging:
#            driver: "json-file"
#        hostname: "localhost"
#        environment:
#           RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        ports:
            - "24224:24224"
            - "24224:24224/udp"
            - "24231:24231"
        volumes:
            - "/media/pi/ext250/fluentd_data:/fluentd/log"

#docker run -d --net=host --name some-fluentd -p 24224:24224 -p 24224:24224/udp -v /media/pi/ext250/fluentd_data:/fluentd/log myfluentd

