version: '3'
services:
    myfluentd:
        build: .
        network_mode: "host"
        container_name: "fluentd"
        logging:
            driver: "${LOGGING_DRIVER:-json-file}"
        ports:
            - "24224:24224"
            - "24224:24224/udp"
            - "24231:24231"
            - "9292:9292"
        volumes:
            - "/media/pi/ext250/fluentd_data:/fluentd/log"
            - "./fluent.conf:/fluentd/etc/fluent.conf"
