http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
log.format: json
#pipeline.workers: 2
xpack.monitoring.elasticsearch.url: http://localhost:9200
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: changeme
