version: '3'

services:
  kibana:
    image: kibana
    network_mode: "host"
    hostname: "kibana"
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
    ports:
      - "5601:5601"
    environment:
        ELASTICSEARCH_URL: "http://localhost:9200" 
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"

#docker run -p 5601:5601 --net host -e ELASTICSEARCH_URL=http://localhost:9200 --name some-kibana -d kibana
