version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    container_name: "kibana"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"

#    hostname: "kibana"
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
    ports:
      - "5601:5601"
#    logging:
#        driver: "json-file"
    environment:
        ELASTICSEARCH_URL: "http://localhost:9200" 
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
