version: '3'

services:
  romek:
    build: logstash/
    container_name: "romek"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    environment:
#        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        LS_BEAT_PORT: "5045"
 

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.2
    container_name: "filebeat"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"  
    volumes:
        - ./logs/:/mnt/logs
        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#       - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml   
#       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
#    ports:
#      - "5601:5601"
#    environment:
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"

