version: '3'
services:
  grafana:
    image: grafana/grafana
#    depends_on:
#      - prometheus
    network_mode: "host"
    ports:
      - 3000:3000
    volumes:
    - /media/pi/ext250/graphana_data:/var/lib/grafana




