version: '3'
services:
  grafana:
    image: grafana/grafana
#    depends_on:
#      - prometheus
    network_mode: "host"
    ports:
      - 3000:3000
    volumes:
    - /media/pi/ext250/graphana_data:/var/lib/grafana




#  netdata:
#    build: ./netdata
#    image: titpetric/netdata
#    volumes:
#    - /proc:/host/proc:ro
#    - /sys:/host/sys:ro
#    - /var/run/docker.sock:/var/run/docker.sock
#    - ./netdata/netdata.conf:/etc/netdata/netdata.conf
#    links:
#    - carbon
#    network_mode: "host"
#    privileged: true
#    ports:
#    - "19999:19999"
#    cap_add:
#    - SYS_PTRACE

#/media/pi/ext250/graphana_data

