version: '3'
services:
    testfluentd:
        build: fluentd/
        network_mode: "host"
        container_name: "test_log_fluentd"
        logging:
            driver: "${LOGGING_DRIVER:-json-file}"
        volumes:
            - "./logs/:/log/"
            - "./fluentd/fluent.conf:/fluentd/etc/fluent.conf"

    testlogstash:
        build: logstash/
        network_mode: "host"
        container_name: "test_log_logstash"
        logging:
            driver: "${LOGGING_DRIVER:-json-file}"
#        volumes:
#            - ./logstash/config:/usr/share/logstash/config
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#            LS_LOG_FORMAT: json 


