version: '3'
services:
    testfluentd:
        build: fluentd/
        network_mode: "host"
        logging:
            driver: "json-file"
        volumes:
            - "/home/pi/Downloads/r24_stdout.log:/log/input_file.log"
            - "./fluentd/fluent.conf:/fluentd/etc/fluent.conf"

    testlogstash:
        build: logstash/
#        image: logstash
        network_mode: "host"
        logging:
            driver: "json-file"
#        volumes:
#            - ./logstash/config:/usr/share/logstash/config
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"

