version: '3'

services:
#  romek:
#    build: logstash/
#    network_mode: "host"
#    logging:
#        driver: "json-file"
#    environment:
#        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#        LS_BEAT_PORT: "5045"
#  atomek:
#    build: logstash/
#    network_mode: "host"
#    logging:
#        driver: "json-file"
#    environment:
#        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#        LS_BEAT_PORT: "5046"
  

  beat:
    build: beat/
    network_mode: "host"
#    depends_on:
#        - romek
    volumes:
#        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - /proc:/hostfs/proc:ro
        - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
        - /:/hostfs:ro
        - ./temp:/usr/share/metricbeat/temp
#    ports:
#      - "5601:5601"
    logging:
        driver: "json-file"
#    environment:
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"

