version: '3'

services:
  elasticsearch:
    build: .
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
    container_name: "elastic"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        discovery.type: "single-node"
        ELASTIC_PASSWORD: "changeme"
