version: '3'

services:
  elasticsearch:
#    image: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    build: .
    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
#    logging:
#        driver: "json-file"
    network_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        discovery.type: "single-node"
        ELASTIC_PASSWORD: "changeme"

#docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.3

#docker run -d --name some-elasticsearch 
#-v /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 elasticsearch
