version: '3'

services:
  fluentd:
    build: fluentd/
    network_mode: "host"
    container_name: "log_fluentd"
    logging:
      driver: "${LOGGING_DRIVER:-json-file}"
    volumes:
      - "/media/pi/ext250/logs/:/log/"
      - "./fluentd/fluent.conf:/fluentd/etc/fluent.conf"
      - /etc/localtime:/etc/localtime:ro
  logstash:
    build: ./logstash
    #image: docker.elastic.co/logstash/logstash:6.2.3
    container_name: "logstash"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    volumes:
        - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./logstash/pipeline:/usr/share/logstash/pipeline
        - /etc/localtime:/etc/localtime:ro
    environment:
        CONFIG_RELOAD_AUTOMATIC: "true"
        XPACK_MONITORING_ENABLED: "true"
        HTTP_HOST: "0.0.0.0"
#        xpack_management_enabled: "true"
#        xpack_management_elasticsearch_url: "http://localhost:9200/"
#        xpack_management_logstash_poll_interval: "5s"
#        xpack_management_elasticsearch_username: "elasticsearch"
#        xpack_management_elasticsearch_password: "changeme"
#        xpack_management_pipeline_id: "['nfc', 'docker_logs']"
#        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    ports:
#     - "9600:9600"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    container_name: "filebeat"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"  
    volumes:
        - /media/pi/ext250/logs/:/mnt/logs
        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - /etc/localtime:/etc/localtime:ro        
 
  elasticsearch:
#    build: .
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
    container_name: "elastic"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
#        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        discovery.type: "single-node"
#        ELASTIC_PASSWORD: "changeme"


  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: "kibana"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    volumes:
        - /etc/localtime:/etc/localtime:ro
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#       - /media/pi/ext250/elastic_data:/usr/share/elasticsearch/data 
    ports:
      - "5601:5601"
    environment:
        ELASTICSEARCH_URL: "http://localhost:9200" 
