version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: "portainer"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    network_mode: "host"
    ports:
        - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
