version: '3'
services:
  mynetdata:
    image: titpetric/netdata
#           firehol/netdata
    container_name: "netdata"
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - ./netdata.conf:/etc/netdata/netdata.conf
        - ./health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf
    network_mode: "host"
    logging:
            driver: "${LOGGING_DRIVER:-json-file}"
    privileged: true
    ports:
        - "19999:19999"
    cap_add:
        - SYS_PTRACE
