version: '3'
services:
  logstash:
    #build: latest/
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    container_name: "logstash"
    network_mode: "host"
    logging:
        driver: "${LOGGING_DRIVER:-json-file}"
    volumes:
        - ./config:/usr/share/logstash/config
        - ./pipeline:/usr/share/logstash/pipeline
#    environment:
#        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    ports:
#     - "9600:9600"

