version: '3'
services:
    chronograf:
        image: "chronograf"
        container_name: "chronograf"
        network_mode: "host"
        logging:
            driver: "${LOGGING_DRIVER:-json-file}"
#        environment:
#           INFLUXDB_DB: "statistics"
#           INFLUXDB_GRAPHITE_ENABLED: "true"
        ports:
            - "8888:8888"
        volumes:
            - "/media/pi/ext250/chronograf_data:/var/lib/chronograf"
