version: '3'
services:
    telegraf:
        image: "telegraf"
        container_name: "telegraf"
        network_mode: "host"
        logging:
            driver: "${LOGGING_DRIVER:-json-file}"
#        environment:
#           INFLUXDB_GRAPHITE_ENABLED: "true"
        ports:
            - "8094:8094"
            - "8092:8092/udp"
        volumes:
            - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"

