version: '3'
services:
    influxdb:
        image: "influxdb"
        container_name: "influxdb"
        network_mode: "host"
        logging:
            driver: "${LOGGING_DRIVER:-json-file}"
        environment:
           INFLUXDB_DB: "statistics"
#           INFLUXDB_GRAPHITE_ENABLED: "true"
        ports:
            - "8086:8086"
            - "2003:2003"
            - "4242:4242"
        volumes:
            - "./influxdb.conf:/etc/influxdb/influxdb.conf:ro"
            - "/media/pi/ext250/influxdb_data:/var/lib/influxdb"

